<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ciudades')->insert([
            ['codigo'=>5001,'nombre'=>'medellín','departamento_id'=>1],
            ['codigo'=>5002,'nombre'=>'abejorral','departamento_id'=>1],
            ['codigo'=>5004,'nombre'=>'abriaquí','departamento_id'=>1],
            ['codigo'=>5021,'nombre'=>'alejandría','departamento_id'=>1],
            ['codigo'=>5030,'nombre'=>'amagá','departamento_id'=>1],
            ['codigo'=>5031,'nombre'=>'amalfi','departamento_id'=>1],
            ['codigo'=>5034,'nombre'=>'andes','departamento_id'=>1],
            ['codigo'=>5036,'nombre'=>'angelópolis','departamento_id'=>1],
            ['codigo'=>5038,'nombre'=>'angostura','departamento_id'=>1],
            ['codigo'=>5040,'nombre'=>'anorí','departamento_id'=>1],
            ['codigo'=>5042,'nombre'=>'santa fé de antioquia','departamento_id'=>1],
            ['codigo'=>5044,'nombre'=>'anzá','departamento_id'=>1],
            ['codigo'=>5045,'nombre'=>'apartadó','departamento_id'=>1],
            ['codigo'=>5051,'nombre'=>'arboletes','departamento_id'=>1],
            ['codigo'=>5055,'nombre'=>'argelia','departamento_id'=>1],
            ['codigo'=>5059,'nombre'=>'armenia','departamento_id'=>1],
            ['codigo'=>5079,'nombre'=>'barbosa','departamento_id'=>1],
            ['codigo'=>5086,'nombre'=>'belmira','departamento_id'=>1],
            ['codigo'=>5088,'nombre'=>'bello','departamento_id'=>1],
            ['codigo'=>5091,'nombre'=>'betania','departamento_id'=>1],
            ['codigo'=>5093,'nombre'=>'betulia','departamento_id'=>1],
            ['codigo'=>5101,'nombre'=>'ciudad bolívar','departamento_id'=>1],
            ['codigo'=>5107,'nombre'=>'briceño','departamento_id'=>1],
            ['codigo'=>5113,'nombre'=>'buriticá','departamento_id'=>1],
            ['codigo'=>5120,'nombre'=>'cáceres','departamento_id'=>1],
            ['codigo'=>5125,'nombre'=>'caicedo','departamento_id'=>1],
            ['codigo'=>5129,'nombre'=>'caldas','departamento_id'=>1],
            ['codigo'=>5134,'nombre'=>'campamento','departamento_id'=>1],
            ['codigo'=>5138,'nombre'=>'cañasgordas','departamento_id'=>1],
            ['codigo'=>5142,'nombre'=>'caracolí','departamento_id'=>1],
            ['codigo'=>5145,'nombre'=>'caramanta','departamento_id'=>1],
            ['codigo'=>5147,'nombre'=>'carepa','departamento_id'=>1],
            ['codigo'=>5148,'nombre'=>'el carmen de viboral','departamento_id'=>1],
            ['codigo'=>5150,'nombre'=>'carolina','departamento_id'=>1],
            ['codigo'=>5154,'nombre'=>'caucasia','departamento_id'=>1],
            ['codigo'=>5172,'nombre'=>'chigorodó','departamento_id'=>1],
            ['codigo'=>5190,'nombre'=>'cisneros','departamento_id'=>1],
            ['codigo'=>5197,'nombre'=>'cocorná','departamento_id'=>1],
            ['codigo'=>5206,'nombre'=>'concepción','departamento_id'=>1],
            ['codigo'=>5209,'nombre'=>'concordia','departamento_id'=>1],
            ['codigo'=>5212,'nombre'=>'copacabana','departamento_id'=>1],
            ['codigo'=>5234,'nombre'=>'dabeiba','departamento_id'=>1],
            ['codigo'=>5237,'nombre'=>'donmatías','departamento_id'=>1],
            ['codigo'=>5240,'nombre'=>'ebéjico','departamento_id'=>1],
            ['codigo'=>5250,'nombre'=>'el bagre','departamento_id'=>1],
            ['codigo'=>5264,'nombre'=>'entrerríos','departamento_id'=>1],
            ['codigo'=>5266,'nombre'=>'envigado','departamento_id'=>1],
            ['codigo'=>5282,'nombre'=>'fredonia','departamento_id'=>1],
            ['codigo'=>5284,'nombre'=>'frontino','departamento_id'=>1],
            ['codigo'=>5306,'nombre'=>'giraldo','departamento_id'=>1],
            ['codigo'=>5308,'nombre'=>'girardota','departamento_id'=>1],
            ['codigo'=>5310,'nombre'=>'gómez plata','departamento_id'=>1],
            ['codigo'=>5313,'nombre'=>'granada','departamento_id'=>1],
            ['codigo'=>5315,'nombre'=>'guadalupe','departamento_id'=>1],
            ['codigo'=>5318,'nombre'=>'guarne','departamento_id'=>1],
            ['codigo'=>5321,'nombre'=>'guatapé','departamento_id'=>1],
            ['codigo'=>5347,'nombre'=>'heliconia','departamento_id'=>1],
            ['codigo'=>5353,'nombre'=>'hispania','departamento_id'=>1],
            ['codigo'=>5360,'nombre'=>'itagüí','departamento_id'=>1],
            ['codigo'=>5361,'nombre'=>'ituango','departamento_id'=>1],
            ['codigo'=>5364,'nombre'=>'jardín','departamento_id'=>1],
            ['codigo'=>5368,'nombre'=>'jericó','departamento_id'=>1],
            ['codigo'=>5376,'nombre'=>'la ceja','departamento_id'=>1],
            ['codigo'=>5380,'nombre'=>'la estrella','departamento_id'=>1],
            ['codigo'=>5390,'nombre'=>'la pintada','departamento_id'=>1],
            ['codigo'=>5400,'nombre'=>'la unión','departamento_id'=>1],
            ['codigo'=>5411,'nombre'=>'liborina','departamento_id'=>1],
            ['codigo'=>5425,'nombre'=>'maceo','departamento_id'=>1],
            ['codigo'=>5440,'nombre'=>'marinilla','departamento_id'=>1],
            ['codigo'=>5467,'nombre'=>'montebello','departamento_id'=>1],
            ['codigo'=>5475,'nombre'=>'murindó','departamento_id'=>1],
            ['codigo'=>5480,'nombre'=>'mutatá','departamento_id'=>1],
            ['codigo'=>5483,'nombre'=>'nariño','departamento_id'=>1],
            ['codigo'=>5490,'nombre'=>'necoclí','departamento_id'=>1],
            ['codigo'=>5495,'nombre'=>'nechí','departamento_id'=>1],
            ['codigo'=>5501,'nombre'=>'olaya','departamento_id'=>1],
            ['codigo'=>5541,'nombre'=>'peñol','departamento_id'=>1],
            ['codigo'=>5543,'nombre'=>'peque','departamento_id'=>1],
            ['codigo'=>5576,'nombre'=>'pueblorrico','departamento_id'=>1],
            ['codigo'=>5579,'nombre'=>'puerto berrío','departamento_id'=>1],
            ['codigo'=>5585,'nombre'=>'puerto nare','departamento_id'=>1],
            ['codigo'=>5591,'nombre'=>'puerto triunfo','departamento_id'=>1],
            ['codigo'=>5604,'nombre'=>'remedios','departamento_id'=>1],
            ['codigo'=>5607,'nombre'=>'retiro','departamento_id'=>1],
            ['codigo'=>5615,'nombre'=>'rionegro','departamento_id'=>1],
            ['codigo'=>5628,'nombre'=>'sabanalarga','departamento_id'=>1],
            ['codigo'=>5631,'nombre'=>'sabaneta','departamento_id'=>1],
            ['codigo'=>5642,'nombre'=>'salgar','departamento_id'=>1],
            ['codigo'=>5647,'nombre'=>'san andrés de cuerquía','departamento_id'=>1],
            ['codigo'=>5649,'nombre'=>'san carlos','departamento_id'=>1],
            ['codigo'=>5652,'nombre'=>'san francisco','departamento_id'=>1],
            ['codigo'=>5656,'nombre'=>'san jerónimo','departamento_id'=>1],
            ['codigo'=>5658,'nombre'=>'san josé de la montaña','departamento_id'=>1],
            ['codigo'=>5659,'nombre'=>'san juan de urabá','departamento_id'=>1],
            ['codigo'=>5660,'nombre'=>'san luis','departamento_id'=>1],
            ['codigo'=>5664,'nombre'=>'san pedro de los milagros','departamento_id'=>1],
            ['codigo'=>5665,'nombre'=>'san pedro de urabá','departamento_id'=>1],
            ['codigo'=>5667,'nombre'=>'san rafael','departamento_id'=>1],
            ['codigo'=>5670,'nombre'=>'san roque','departamento_id'=>1],
            ['codigo'=>5674,'nombre'=>'san vicente ferrer','departamento_id'=>1],
            ['codigo'=>5679,'nombre'=>'santa bárbara','departamento_id'=>1],
            ['codigo'=>5686,'nombre'=>'santa rosa de osos','departamento_id'=>1],
            ['codigo'=>5690,'nombre'=>'santo domingo','departamento_id'=>1],
            ['codigo'=>5697,'nombre'=>'el santuario','departamento_id'=>1],
            ['codigo'=>5736,'nombre'=>'segovia','departamento_id'=>1],
            ['codigo'=>5756,'nombre'=>'sonsón','departamento_id'=>1],
            ['codigo'=>5761,'nombre'=>'sopetrán','departamento_id'=>1],
            ['codigo'=>5789,'nombre'=>'támesis','departamento_id'=>1],
            ['codigo'=>5790,'nombre'=>'tarazá','departamento_id'=>1],
            ['codigo'=>5792,'nombre'=>'tarso','departamento_id'=>1],
            ['codigo'=>5809,'nombre'=>'titiribí','departamento_id'=>1],
            ['codigo'=>5819,'nombre'=>'toledo','departamento_id'=>1],
            ['codigo'=>5837,'nombre'=>'turbo','departamento_id'=>1],
            ['codigo'=>5842,'nombre'=>'uramita','departamento_id'=>1],
            ['codigo'=>5847,'nombre'=>'urrao','departamento_id'=>1],
            ['codigo'=>5854,'nombre'=>'valdivia','departamento_id'=>1],
            ['codigo'=>5856,'nombre'=>'valparaíso','departamento_id'=>1],
            ['codigo'=>5858,'nombre'=>'vegachí','departamento_id'=>1],
            ['codigo'=>5861,'nombre'=>'venecia','departamento_id'=>1],
            ['codigo'=>5873,'nombre'=>'vigía del fuerte','departamento_id'=>1],
            ['codigo'=>5885,'nombre'=>'yalí','departamento_id'=>1],
            ['codigo'=>5887,'nombre'=>'yarumal','departamento_id'=>1],
            ['codigo'=>5890,'nombre'=>'yolombó','departamento_id'=>1],
            ['codigo'=>5893,'nombre'=>'yondó','departamento_id'=>1],
            ['codigo'=>5895,'nombre'=>'zaragoza','departamento_id'=>1],
            ['codigo'=>8001,'nombre'=>'barranquilla','departamento_id'=>2],
            ['codigo'=>8078,'nombre'=>'baranoa','departamento_id'=>2],
            ['codigo'=>8137,'nombre'=>'campo de la cruz','departamento_id'=>2],
            ['codigo'=>8141,'nombre'=>'candelaria','departamento_id'=>2],
            ['codigo'=>8296,'nombre'=>'galapa','departamento_id'=>2],
            ['codigo'=>8372,'nombre'=>'juan de acosta','departamento_id'=>2],
            ['codigo'=>8421,'nombre'=>'luruaco','departamento_id'=>2],
            ['codigo'=>8433,'nombre'=>'malambo','departamento_id'=>2],
            ['codigo'=>8436,'nombre'=>'manatí','departamento_id'=>2],
            ['codigo'=>8520,'nombre'=>'palmar de varela','departamento_id'=>2],
            ['codigo'=>8549,'nombre'=>'piojó','departamento_id'=>2],
            ['codigo'=>8558,'nombre'=>'polonuevo','departamento_id'=>2],
            ['codigo'=>8560,'nombre'=>'ponedera','departamento_id'=>2],
            ['codigo'=>8573,'nombre'=>'puerto colombia','departamento_id'=>2],
            ['codigo'=>8606,'nombre'=>'repelón','departamento_id'=>2],
            ['codigo'=>8634,'nombre'=>'sabanagrande','departamento_id'=>2],
            ['codigo'=>8638,'nombre'=>'sabanalarga','departamento_id'=>2],
            ['codigo'=>8675,'nombre'=>'santa lucía','departamento_id'=>2],
            ['codigo'=>8685,'nombre'=>'santo tomás','departamento_id'=>2],
            ['codigo'=>8758,'nombre'=>'soledad','departamento_id'=>2],
            ['codigo'=>8770,'nombre'=>'suan','departamento_id'=>2],
            ['codigo'=>8832,'nombre'=>'tubará','departamento_id'=>2],
            ['codigo'=>8849,'nombre'=>'usiacurí','departamento_id'=>2],
            ['codigo'=>11001,'nombre'=>'bogotá, d.c.','departamento_id'=>3],
            ['codigo'=>13001,'nombre'=>'cartagena de indias','departamento_id'=>4],
            ['codigo'=>13006,'nombre'=>'achí','departamento_id'=>4],
            ['codigo'=>13030,'nombre'=>'altos del rosario','departamento_id'=>4],
            ['codigo'=>13042,'nombre'=>'arenal','departamento_id'=>4],
            ['codigo'=>13052,'nombre'=>'arjona','departamento_id'=>4],
            ['codigo'=>13062,'nombre'=>'arroyohondo','departamento_id'=>4],
            ['codigo'=>13074,'nombre'=>'barranco de loba','departamento_id'=>4],
            ['codigo'=>13140,'nombre'=>'calamar','departamento_id'=>4],
            ['codigo'=>13160,'nombre'=>'cantagallo','departamento_id'=>4],
            ['codigo'=>13188,'nombre'=>'cicuco','departamento_id'=>4],
            ['codigo'=>13212,'nombre'=>'córdoba','departamento_id'=>4],
            ['codigo'=>13222,'nombre'=>'clemencia','departamento_id'=>4],
            ['codigo'=>13244,'nombre'=>'el carmen de bolívar','departamento_id'=>4],
            ['codigo'=>13248,'nombre'=>'el guamo','departamento_id'=>4],
            ['codigo'=>13268,'nombre'=>'el peñón','departamento_id'=>4],
            ['codigo'=>13300,'nombre'=>'hatillo de loba','departamento_id'=>4],
            ['codigo'=>13430,'nombre'=>'magangué','departamento_id'=>4],
            ['codigo'=>13433,'nombre'=>'mahates','departamento_id'=>4],
            ['codigo'=>13440,'nombre'=>'margarita','departamento_id'=>4],
            ['codigo'=>13442,'nombre'=>'maría la baja','departamento_id'=>4],
            ['codigo'=>13458,'nombre'=>'montecristo','departamento_id'=>4],
            ['codigo'=>13468,'nombre'=>'mompós','departamento_id'=>4],
            ['codigo'=>13473,'nombre'=>'morales','departamento_id'=>4],
            ['codigo'=>13490,'nombre'=>'norosí','departamento_id'=>4],
            ['codigo'=>13549,'nombre'=>'pinillos','departamento_id'=>4],
            ['codigo'=>13580,'nombre'=>'regidor','departamento_id'=>4],
            ['codigo'=>13600,'nombre'=>'río viejo','departamento_id'=>4],
            ['codigo'=>13620,'nombre'=>'san cristóbal','departamento_id'=>4],
            ['codigo'=>13647,'nombre'=>'san estanislao','departamento_id'=>4],
            ['codigo'=>13650,'nombre'=>'san fernando','departamento_id'=>4],
            ['codigo'=>13654,'nombre'=>'san jacinto','departamento_id'=>4],
            ['codigo'=>13655,'nombre'=>'san jacinto del cauca','departamento_id'=>4],
            ['codigo'=>13657,'nombre'=>'san juan nepomuceno','departamento_id'=>4],
            ['codigo'=>13667,'nombre'=>'san martín de loba','departamento_id'=>4],
            ['codigo'=>13670,'nombre'=>'san pablo','departamento_id'=>4],
            ['codigo'=>13673,'nombre'=>'santa catalina','departamento_id'=>4],
            ['codigo'=>13683,'nombre'=>'santa rosa','departamento_id'=>4],
            ['codigo'=>13688,'nombre'=>'santa rosa del sur','departamento_id'=>4],
            ['codigo'=>13744,'nombre'=>'simití','departamento_id'=>4],
            ['codigo'=>13760,'nombre'=>'soplaviento','departamento_id'=>4],
            ['codigo'=>13780,'nombre'=>'talaigua nuevo','departamento_id'=>4],
            ['codigo'=>13810,'nombre'=>'tiquisio','departamento_id'=>4],
            ['codigo'=>13836,'nombre'=>'turbaco','departamento_id'=>4],
            ['codigo'=>13838,'nombre'=>'turbaná','departamento_id'=>4],
            ['codigo'=>13873,'nombre'=>'villanueva','departamento_id'=>4],
            ['codigo'=>13894,'nombre'=>'zambrano','departamento_id'=>4],
            ['codigo'=>15001,'nombre'=>'tunja','departamento_id'=>5],
            ['codigo'=>15022,'nombre'=>'almeida','departamento_id'=>5],
            ['codigo'=>15047,'nombre'=>'aquitania','departamento_id'=>5],
            ['codigo'=>15051,'nombre'=>'arcabuco','departamento_id'=>5],
            ['codigo'=>15087,'nombre'=>'belén','departamento_id'=>5],
            ['codigo'=>15090,'nombre'=>'berbeo','departamento_id'=>5],
            ['codigo'=>15092,'nombre'=>'betéitiva','departamento_id'=>5],
            ['codigo'=>15097,'nombre'=>'boavita','departamento_id'=>5],
            ['codigo'=>15104,'nombre'=>'boyacá','departamento_id'=>5],
            ['codigo'=>15106,'nombre'=>'briceño','departamento_id'=>5],
            ['codigo'=>15109,'nombre'=>'buenavista','departamento_id'=>5],
            ['codigo'=>15114,'nombre'=>'busbanzá','departamento_id'=>5],
            ['codigo'=>15131,'nombre'=>'caldas','departamento_id'=>5],
            ['codigo'=>15135,'nombre'=>'campohermoso','departamento_id'=>5],
            ['codigo'=>15162,'nombre'=>'cerinza','departamento_id'=>5],
            ['codigo'=>15172,'nombre'=>'chinavita','departamento_id'=>5],
            ['codigo'=>15176,'nombre'=>'chiquinquirá','departamento_id'=>5],
            ['codigo'=>15180,'nombre'=>'chiscas','departamento_id'=>5],
            ['codigo'=>15183,'nombre'=>'chita','departamento_id'=>5],
            ['codigo'=>15185,'nombre'=>'chitaraque','departamento_id'=>5],
            ['codigo'=>15187,'nombre'=>'chivatá','departamento_id'=>5],
            ['codigo'=>15189,'nombre'=>'ciénega','departamento_id'=>5],
            ['codigo'=>15204,'nombre'=>'cómbita','departamento_id'=>5],
            ['codigo'=>15212,'nombre'=>'coper','departamento_id'=>5],
            ['codigo'=>15215,'nombre'=>'corrales','departamento_id'=>5],
            ['codigo'=>15218,'nombre'=>'covarachía','departamento_id'=>5],
            ['codigo'=>15223,'nombre'=>'cubará','departamento_id'=>5],
            ['codigo'=>15224,'nombre'=>'cucaita','departamento_id'=>5],
            ['codigo'=>15226,'nombre'=>'cuítiva','departamento_id'=>5],
            ['codigo'=>15232,'nombre'=>'chíquiza','departamento_id'=>5],
            ['codigo'=>15236,'nombre'=>'chivor','departamento_id'=>5],
            ['codigo'=>15238,'nombre'=>'duitama','departamento_id'=>5],
            ['codigo'=>15244,'nombre'=>'el cocuy','departamento_id'=>5],
            ['codigo'=>15248,'nombre'=>'el espino','departamento_id'=>5],
            ['codigo'=>15272,'nombre'=>'firavitoba','departamento_id'=>5],
            ['codigo'=>15276,'nombre'=>'floresta','departamento_id'=>5],
            ['codigo'=>15293,'nombre'=>'gachantivá','departamento_id'=>5],
            ['codigo'=>15296,'nombre'=>'gámeza','departamento_id'=>5],
            ['codigo'=>15299,'nombre'=>'garagoa','departamento_id'=>5],
            ['codigo'=>15317,'nombre'=>'guacamayas','departamento_id'=>5],
            ['codigo'=>15322,'nombre'=>'guateque','departamento_id'=>5],
            ['codigo'=>15325,'nombre'=>'guayatá','departamento_id'=>5],
            ['codigo'=>15332,'nombre'=>'güicán de la sierra','departamento_id'=>5],
            ['codigo'=>15362,'nombre'=>'iza','departamento_id'=>5],
            ['codigo'=>15367,'nombre'=>'jenesano','departamento_id'=>5],
            ['codigo'=>15368,'nombre'=>'jericó','departamento_id'=>5],
            ['codigo'=>15377,'nombre'=>'labranzagrande','departamento_id'=>5],
            ['codigo'=>15380,'nombre'=>'la capilla','departamento_id'=>5],
            ['codigo'=>15401,'nombre'=>'la victoria','departamento_id'=>5],
            ['codigo'=>15403,'nombre'=>'la uvita','departamento_id'=>5],
            ['codigo'=>15407,'nombre'=>'villa de leyva','departamento_id'=>5],
            ['codigo'=>15425,'nombre'=>'macanal','departamento_id'=>5],
            ['codigo'=>15442,'nombre'=>'maripí','departamento_id'=>5],
            ['codigo'=>15455,'nombre'=>'miraflores','departamento_id'=>5],
            ['codigo'=>15464,'nombre'=>'mongua','departamento_id'=>5],
            ['codigo'=>15466,'nombre'=>'monguí','departamento_id'=>5],
            ['codigo'=>15469,'nombre'=>'moniquirá','departamento_id'=>5],
            ['codigo'=>15476,'nombre'=>'motavita','departamento_id'=>5],
            ['codigo'=>15480,'nombre'=>'muzo','departamento_id'=>5],
            ['codigo'=>15491,'nombre'=>'nobsa','departamento_id'=>5],
            ['codigo'=>15494,'nombre'=>'nuevo colón','departamento_id'=>5],
            ['codigo'=>15500,'nombre'=>'oicatá','departamento_id'=>5],
            ['codigo'=>15507,'nombre'=>'otanche','departamento_id'=>5],
            ['codigo'=>15511,'nombre'=>'pachavita','departamento_id'=>5],
            ['codigo'=>15514,'nombre'=>'páez','departamento_id'=>5],
            ['codigo'=>15516,'nombre'=>'paipa','departamento_id'=>5],
            ['codigo'=>15518,'nombre'=>'pajarito','departamento_id'=>5],
            ['codigo'=>15522,'nombre'=>'panqueba','departamento_id'=>5],
            ['codigo'=>15531,'nombre'=>'pauna','departamento_id'=>5],
            ['codigo'=>15533,'nombre'=>'paya','departamento_id'=>5],
            ['codigo'=>15537,'nombre'=>'paz de río','departamento_id'=>5],
            ['codigo'=>15542,'nombre'=>'pesca','departamento_id'=>5],
            ['codigo'=>15550,'nombre'=>'pisba','departamento_id'=>5],
            ['codigo'=>15572,'nombre'=>'puerto boyacá','departamento_id'=>5],
            ['codigo'=>15580,'nombre'=>'quípama','departamento_id'=>5],
            ['codigo'=>15599,'nombre'=>'ramiriquí','departamento_id'=>5],
            ['codigo'=>15600,'nombre'=>'ráquira','departamento_id'=>5],
            ['codigo'=>15621,'nombre'=>'rondón','departamento_id'=>5],
            ['codigo'=>15632,'nombre'=>'saboyá','departamento_id'=>5],
            ['codigo'=>15638,'nombre'=>'sáchica','departamento_id'=>5],
            ['codigo'=>15646,'nombre'=>'samacá','departamento_id'=>5],
            ['codigo'=>15660,'nombre'=>'san eduardo','departamento_id'=>5],
            ['codigo'=>15664,'nombre'=>'san josé de pare','departamento_id'=>5],
            ['codigo'=>15667,'nombre'=>'san luis de gaceno','departamento_id'=>5],
            ['codigo'=>15673,'nombre'=>'san mateo','departamento_id'=>5],
            ['codigo'=>15676,'nombre'=>'san miguel de sema','departamento_id'=>5],
            ['codigo'=>15681,'nombre'=>'san pablo de borbur','departamento_id'=>5],
            ['codigo'=>15686,'nombre'=>'santana','departamento_id'=>5],
            ['codigo'=>15690,'nombre'=>'santa maría','departamento_id'=>5],
            ['codigo'=>15693,'nombre'=>'santa rosa de viterbo','departamento_id'=>5],
            ['codigo'=>15696,'nombre'=>'santa sofía','departamento_id'=>5],
            ['codigo'=>15720,'nombre'=>'sativanorte','departamento_id'=>5],
            ['codigo'=>15723,'nombre'=>'sativasur','departamento_id'=>5],
            ['codigo'=>15740,'nombre'=>'siachoque','departamento_id'=>5],
            ['codigo'=>15753,'nombre'=>'soatá','departamento_id'=>5],
            ['codigo'=>15755,'nombre'=>'socotá','departamento_id'=>5],
            ['codigo'=>15757,'nombre'=>'socha','departamento_id'=>5],
            ['codigo'=>15759,'nombre'=>'sogamoso','departamento_id'=>5],
            ['codigo'=>15761,'nombre'=>'somondoco','departamento_id'=>5],
            ['codigo'=>15762,'nombre'=>'sora','departamento_id'=>5],
            ['codigo'=>15763,'nombre'=>'sotaquirá','departamento_id'=>5],
            ['codigo'=>15764,'nombre'=>'soracá','departamento_id'=>5],
            ['codigo'=>15774,'nombre'=>'susacón','departamento_id'=>5],
            ['codigo'=>15776,'nombre'=>'sutamarchán','departamento_id'=>5],
            ['codigo'=>15778,'nombre'=>'sutatenza','departamento_id'=>5],
            ['codigo'=>15790,'nombre'=>'tasco','departamento_id'=>5],
            ['codigo'=>15798,'nombre'=>'tenza','departamento_id'=>5],
            ['codigo'=>15804,'nombre'=>'tibaná','departamento_id'=>5],
            ['codigo'=>15806,'nombre'=>'tibasosa','departamento_id'=>5],
            ['codigo'=>15808,'nombre'=>'tinjacá','departamento_id'=>5],
            ['codigo'=>15810,'nombre'=>'tipacoque','departamento_id'=>5],
            ['codigo'=>15814,'nombre'=>'toca','departamento_id'=>5],
            ['codigo'=>15816,'nombre'=>'togüí','departamento_id'=>5],
            ['codigo'=>15820,'nombre'=>'tópaga','departamento_id'=>5],
            ['codigo'=>15822,'nombre'=>'tota','departamento_id'=>5],
            ['codigo'=>15832,'nombre'=>'tununguá','departamento_id'=>5],
            ['codigo'=>15835,'nombre'=>'turmequé','departamento_id'=>5],
            ['codigo'=>15837,'nombre'=>'tuta','departamento_id'=>5],
            ['codigo'=>15839,'nombre'=>'tutazá','departamento_id'=>5],
            ['codigo'=>15842,'nombre'=>'úmbita','departamento_id'=>5],
            ['codigo'=>15861,'nombre'=>'ventaquemada','departamento_id'=>5],
            ['codigo'=>15879,'nombre'=>'viracachá','departamento_id'=>5],
            ['codigo'=>15897,'nombre'=>'zetaquira','departamento_id'=>5],
            ['codigo'=>17001,'nombre'=>'manizales','departamento_id'=>6],
            ['codigo'=>17013,'nombre'=>'aguadas','departamento_id'=>6],
            ['codigo'=>17042,'nombre'=>'anserma','departamento_id'=>6],
            ['codigo'=>17050,'nombre'=>'aranzazu','departamento_id'=>6],
            ['codigo'=>17088,'nombre'=>'belalcázar','departamento_id'=>6],
            ['codigo'=>17174,'nombre'=>'chinchiná','departamento_id'=>6],
            ['codigo'=>17272,'nombre'=>'filadelfia','departamento_id'=>6],
            ['codigo'=>17380,'nombre'=>'la dorada','departamento_id'=>6],
            ['codigo'=>17388,'nombre'=>'la merced','departamento_id'=>6],
            ['codigo'=>17433,'nombre'=>'manzanares','departamento_id'=>6],
            ['codigo'=>17442,'nombre'=>'marmato','departamento_id'=>6],
            ['codigo'=>17444,'nombre'=>'marquetalia','departamento_id'=>6],
            ['codigo'=>17446,'nombre'=>'marulanda','departamento_id'=>6],
            ['codigo'=>17486,'nombre'=>'neira','departamento_id'=>6],
            ['codigo'=>17495,'nombre'=>'norcasia','departamento_id'=>6],
            ['codigo'=>17513,'nombre'=>'pácora','departamento_id'=>6],
            ['codigo'=>17524,'nombre'=>'palestina','departamento_id'=>6],
            ['codigo'=>17541,'nombre'=>'pensilvania','departamento_id'=>6],
            ['codigo'=>17614,'nombre'=>'riosucio','departamento_id'=>6],
            ['codigo'=>17616,'nombre'=>'risaralda','departamento_id'=>6],
            ['codigo'=>17653,'nombre'=>'salamina','departamento_id'=>6],
            ['codigo'=>17662,'nombre'=>'samaná','departamento_id'=>6],
            ['codigo'=>17665,'nombre'=>'san josé','departamento_id'=>6],
            ['codigo'=>17777,'nombre'=>'supía','departamento_id'=>6],
            ['codigo'=>17867,'nombre'=>'victoria','departamento_id'=>6],
            ['codigo'=>17873,'nombre'=>'villamaría','departamento_id'=>6],
            ['codigo'=>17877,'nombre'=>'viterbo','departamento_id'=>6],
            ['codigo'=>18001,'nombre'=>'florencia','departamento_id'=>7],
            ['codigo'=>18029,'nombre'=>'albania','departamento_id'=>7],
            ['codigo'=>18094,'nombre'=>'belén de los andaquíes','departamento_id'=>7],
            ['codigo'=>18150,'nombre'=>'cartagena del chairá','departamento_id'=>7],
            ['codigo'=>18205,'nombre'=>'curillo','departamento_id'=>7],
            ['codigo'=>18247,'nombre'=>'el doncello','departamento_id'=>7],
            ['codigo'=>18256,'nombre'=>'el paujíl','departamento_id'=>7],
            ['codigo'=>18410,'nombre'=>'la montañita','departamento_id'=>7],
            ['codigo'=>18460,'nombre'=>'milán','departamento_id'=>7],
            ['codigo'=>18479,'nombre'=>'morelia','departamento_id'=>7],
            ['codigo'=>18592,'nombre'=>'puerto rico','departamento_id'=>7],
            ['codigo'=>18610,'nombre'=>'san josé del fragua','departamento_id'=>7],
            ['codigo'=>18753,'nombre'=>'san vicente del caguán','departamento_id'=>7],
            ['codigo'=>18756,'nombre'=>'solano','departamento_id'=>7],
            ['codigo'=>18785,'nombre'=>'solita','departamento_id'=>7],
            ['codigo'=>18860,'nombre'=>'valparaíso','departamento_id'=>7],
            ['codigo'=>19001,'nombre'=>'popayán','departamento_id'=>8],
            ['codigo'=>19022,'nombre'=>'almaguer','departamento_id'=>8],
            ['codigo'=>19050,'nombre'=>'argelia','departamento_id'=>8],
            ['codigo'=>19075,'nombre'=>'balboa','departamento_id'=>8],
            ['codigo'=>19100,'nombre'=>'bolívar','departamento_id'=>8],
            ['codigo'=>19110,'nombre'=>'buenos aires','departamento_id'=>8],
            ['codigo'=>19130,'nombre'=>'cajibío','departamento_id'=>8],
            ['codigo'=>19137,'nombre'=>'caldono','departamento_id'=>8],
            ['codigo'=>19142,'nombre'=>'caloto','departamento_id'=>8],
            ['codigo'=>19212,'nombre'=>'corinto','departamento_id'=>8],
            ['codigo'=>19256,'nombre'=>'el tambo','departamento_id'=>8],
            ['codigo'=>19290,'nombre'=>'florencia','departamento_id'=>8],
            ['codigo'=>19300,'nombre'=>'guachené','departamento_id'=>8],
            ['codigo'=>19318,'nombre'=>'guapí','departamento_id'=>8],
            ['codigo'=>19355,'nombre'=>'inzá','departamento_id'=>8],
            ['codigo'=>19364,'nombre'=>'jambaló','departamento_id'=>8],
            ['codigo'=>19392,'nombre'=>'la sierra','departamento_id'=>8],
            ['codigo'=>19397,'nombre'=>'la vega','departamento_id'=>8],
            ['codigo'=>19418,'nombre'=>'lópez de micay','departamento_id'=>8],
            ['codigo'=>19450,'nombre'=>'mercaderes','departamento_id'=>8],
            ['codigo'=>19455,'nombre'=>'miranda','departamento_id'=>8],
            ['codigo'=>19473,'nombre'=>'morales','departamento_id'=>8],
            ['codigo'=>19513,'nombre'=>'padilla','departamento_id'=>8],
            ['codigo'=>19517,'nombre'=>'páez','departamento_id'=>8],
            ['codigo'=>19532,'nombre'=>'patía','departamento_id'=>8],
            ['codigo'=>19533,'nombre'=>'piamonte','departamento_id'=>8],
            ['codigo'=>19548,'nombre'=>'piendamó','departamento_id'=>8],
            ['codigo'=>19573,'nombre'=>'puerto tejada','departamento_id'=>8],
            ['codigo'=>19585,'nombre'=>'puracé','departamento_id'=>8],
            ['codigo'=>19622,'nombre'=>'rosas','departamento_id'=>8],
            ['codigo'=>19693,'nombre'=>'san sebastián','departamento_id'=>8],
            ['codigo'=>19698,'nombre'=>'santander de quilichao','departamento_id'=>8],
            ['codigo'=>19701,'nombre'=>'santa rosa','departamento_id'=>8],
            ['codigo'=>19743,'nombre'=>'silvia','departamento_id'=>8],
            ['codigo'=>19760,'nombre'=>'sotara','departamento_id'=>8],
            ['codigo'=>19780,'nombre'=>'suárez','departamento_id'=>8],
            ['codigo'=>19785,'nombre'=>'sucre','departamento_id'=>8],
            ['codigo'=>19807,'nombre'=>'timbío','departamento_id'=>8],
            ['codigo'=>19809,'nombre'=>'timbiquí','departamento_id'=>8],
            ['codigo'=>19821,'nombre'=>'toribío','departamento_id'=>8],
            ['codigo'=>19824,'nombre'=>'totoró','departamento_id'=>8],
            ['codigo'=>19845,'nombre'=>'villa rica','departamento_id'=>8],
            ['codigo'=>20001,'nombre'=>'valledupar','departamento_id'=>9],
            ['codigo'=>20011,'nombre'=>'aguachica','departamento_id'=>9],
            ['codigo'=>20013,'nombre'=>'agustín codazzi','departamento_id'=>9],
            ['codigo'=>20032,'nombre'=>'astrea','departamento_id'=>9],
            ['codigo'=>20045,'nombre'=>'becerril','departamento_id'=>9],
            ['codigo'=>20060,'nombre'=>'bosconia','departamento_id'=>9],
            ['codigo'=>20175,'nombre'=>'chimichagua','departamento_id'=>9],
            ['codigo'=>20178,'nombre'=>'chiriguaná','departamento_id'=>9],
            ['codigo'=>20228,'nombre'=>'curumaní','departamento_id'=>9],
            ['codigo'=>20238,'nombre'=>'el copey','departamento_id'=>9],
            ['codigo'=>20250,'nombre'=>'el paso','departamento_id'=>9],
            ['codigo'=>20295,'nombre'=>'gamarra','departamento_id'=>9],
            ['codigo'=>20310,'nombre'=>'gonzález','departamento_id'=>9],
            ['codigo'=>20383,'nombre'=>'la gloria','departamento_id'=>9],
            ['codigo'=>20400,'nombre'=>'la jagua de ibirico','departamento_id'=>9],
            ['codigo'=>20443,'nombre'=>'manaure balcón del cesar','departamento_id'=>9],
            ['codigo'=>20517,'nombre'=>'pailitas','departamento_id'=>9],
            ['codigo'=>20550,'nombre'=>'pelaya','departamento_id'=>9],
            ['codigo'=>20570,'nombre'=>'pueblo bello','departamento_id'=>9],
            ['codigo'=>20614,'nombre'=>'río de oro','departamento_id'=>9],
            ['codigo'=>20621,'nombre'=>'la paz','departamento_id'=>9],
            ['codigo'=>20710,'nombre'=>'san alberto','departamento_id'=>9],
            ['codigo'=>20750,'nombre'=>'san diego','departamento_id'=>9],
            ['codigo'=>20770,'nombre'=>'san martín','departamento_id'=>9],
            ['codigo'=>20787,'nombre'=>'tamalameque','departamento_id'=>9],
            ['codigo'=>23001,'nombre'=>'montería','departamento_id'=>10],
            ['codigo'=>23068,'nombre'=>'ayapel','departamento_id'=>10],
            ['codigo'=>23079,'nombre'=>'buenavista','departamento_id'=>10],
            ['codigo'=>23090,'nombre'=>'canalete','departamento_id'=>10],
            ['codigo'=>23162,'nombre'=>'cereté','departamento_id'=>10],
            ['codigo'=>23168,'nombre'=>'chimá','departamento_id'=>10],
            ['codigo'=>23182,'nombre'=>'chinú','departamento_id'=>10],
            ['codigo'=>23189,'nombre'=>'ciénaga de oro','departamento_id'=>10],
            ['codigo'=>23300,'nombre'=>'cotorra','departamento_id'=>10],
            ['codigo'=>23350,'nombre'=>'la apartada','departamento_id'=>10],
            ['codigo'=>23417,'nombre'=>'lorica','departamento_id'=>10],
            ['codigo'=>23419,'nombre'=>'los córdobas','departamento_id'=>10],
            ['codigo'=>23464,'nombre'=>'momil','departamento_id'=>10],
            ['codigo'=>23466,'nombre'=>'montelíbano','departamento_id'=>10],
            ['codigo'=>23500,'nombre'=>'moñitos','departamento_id'=>10],
            ['codigo'=>23555,'nombre'=>'planeta rica','departamento_id'=>10],
            ['codigo'=>23570,'nombre'=>'pueblo nuevo','departamento_id'=>10],
            ['codigo'=>23574,'nombre'=>'puerto escondido','departamento_id'=>10],
            ['codigo'=>23580,'nombre'=>'puerto libertador','departamento_id'=>10],
            ['codigo'=>23586,'nombre'=>'purísima de la concepción','departamento_id'=>10],
            ['codigo'=>23660,'nombre'=>'sahagún','departamento_id'=>10],
            ['codigo'=>23670,'nombre'=>'san andrés de sotavento','departamento_id'=>10],
            ['codigo'=>23672,'nombre'=>'san antero','departamento_id'=>10],
            ['codigo'=>23675,'nombre'=>'san bernardo del viento','departamento_id'=>10],
            ['codigo'=>23678,'nombre'=>'san carlos','departamento_id'=>10],
            ['codigo'=>23682,'nombre'=>'san josé de uré','departamento_id'=>10],
            ['codigo'=>23686,'nombre'=>'san pelayo','departamento_id'=>10],
            ['codigo'=>23807,'nombre'=>'tierralta','departamento_id'=>10],
            ['codigo'=>23815,'nombre'=>'tuchín','departamento_id'=>10],
            ['codigo'=>23855,'nombre'=>'valencia','departamento_id'=>10],
            ['codigo'=>25001,'nombre'=>'agua de dios','departamento_id'=>11],
            ['codigo'=>25019,'nombre'=>'albán','departamento_id'=>11],
            ['codigo'=>25035,'nombre'=>'anapoima','departamento_id'=>11],
            ['codigo'=>25040,'nombre'=>'anolaima','departamento_id'=>11],
            ['codigo'=>25053,'nombre'=>'arbeláez','departamento_id'=>11],
            ['codigo'=>25086,'nombre'=>'beltrán','departamento_id'=>11],
            ['codigo'=>25095,'nombre'=>'bituima','departamento_id'=>11],
            ['codigo'=>25099,'nombre'=>'bojacá','departamento_id'=>11],
            ['codigo'=>25120,'nombre'=>'cabrera','departamento_id'=>11],
            ['codigo'=>25123,'nombre'=>'cachipay','departamento_id'=>11],
            ['codigo'=>25126,'nombre'=>'cajicá','departamento_id'=>11],
            ['codigo'=>25148,'nombre'=>'caparrapí','departamento_id'=>11],
            ['codigo'=>25151,'nombre'=>'cáqueza','departamento_id'=>11],
            ['codigo'=>25154,'nombre'=>'carmen de carupa','departamento_id'=>11],
            ['codigo'=>25168,'nombre'=>'chaguaní','departamento_id'=>11],
            ['codigo'=>25175,'nombre'=>'chía','departamento_id'=>11],
            ['codigo'=>25178,'nombre'=>'chipaque','departamento_id'=>11],
            ['codigo'=>25181,'nombre'=>'choachí','departamento_id'=>11],
            ['codigo'=>25183,'nombre'=>'chocontá','departamento_id'=>11],
            ['codigo'=>25200,'nombre'=>'cogua','departamento_id'=>11],
            ['codigo'=>25214,'nombre'=>'cota','departamento_id'=>11],
            ['codigo'=>25224,'nombre'=>'cucunubá','departamento_id'=>11],
            ['codigo'=>25245,'nombre'=>'el colegio','departamento_id'=>11],
            ['codigo'=>25258,'nombre'=>'el peñón','departamento_id'=>11],
            ['codigo'=>25260,'nombre'=>'el rosal','departamento_id'=>11],
            ['codigo'=>25269,'nombre'=>'facatativá','departamento_id'=>11],
            ['codigo'=>25279,'nombre'=>'fómeque','departamento_id'=>11],
            ['codigo'=>25281,'nombre'=>'fosca','departamento_id'=>11],
            ['codigo'=>25286,'nombre'=>'funza','departamento_id'=>11],
            ['codigo'=>25288,'nombre'=>'fúquene','departamento_id'=>11],
            ['codigo'=>25290,'nombre'=>'fusagasugá','departamento_id'=>11],
            ['codigo'=>25293,'nombre'=>'gachalá','departamento_id'=>11],
            ['codigo'=>25295,'nombre'=>'gachancipá','departamento_id'=>11],
            ['codigo'=>25297,'nombre'=>'gachetá','departamento_id'=>11],
            ['codigo'=>25299,'nombre'=>'gama','departamento_id'=>11],
            ['codigo'=>25307,'nombre'=>'girardot','departamento_id'=>11],
            ['codigo'=>25312,'nombre'=>'granada','departamento_id'=>11],
            ['codigo'=>25317,'nombre'=>'guachetá','departamento_id'=>11],
            ['codigo'=>25320,'nombre'=>'guaduas','departamento_id'=>11],
            ['codigo'=>25322,'nombre'=>'guasca','departamento_id'=>11],
            ['codigo'=>25324,'nombre'=>'guataquí','departamento_id'=>11],
            ['codigo'=>25326,'nombre'=>'guatavita','departamento_id'=>11],
            ['codigo'=>25328,'nombre'=>'guayabal de síquima','departamento_id'=>11],
            ['codigo'=>25335,'nombre'=>'guayabetal','departamento_id'=>11],
            ['codigo'=>25339,'nombre'=>'gutiérrez','departamento_id'=>11],
            ['codigo'=>25368,'nombre'=>'jerusalén','departamento_id'=>11],
            ['codigo'=>25372,'nombre'=>'junín','departamento_id'=>11],
            ['codigo'=>25377,'nombre'=>'la calera','departamento_id'=>11],
            ['codigo'=>25386,'nombre'=>'la mesa','departamento_id'=>11],
            ['codigo'=>25394,'nombre'=>'la palma','departamento_id'=>11],
            ['codigo'=>25398,'nombre'=>'la peña','departamento_id'=>11],
            ['codigo'=>25402,'nombre'=>'la vega','departamento_id'=>11],
            ['codigo'=>25407,'nombre'=>'lenguazaque','departamento_id'=>11],
            ['codigo'=>25426,'nombre'=>'machetá','departamento_id'=>11],
            ['codigo'=>25430,'nombre'=>'madrid','departamento_id'=>11],
            ['codigo'=>25436,'nombre'=>'manta','departamento_id'=>11],
            ['codigo'=>25438,'nombre'=>'medina','departamento_id'=>11],
            ['codigo'=>25473,'nombre'=>'mosquera','departamento_id'=>11],
            ['codigo'=>25483,'nombre'=>'nariño','departamento_id'=>11],
            ['codigo'=>25486,'nombre'=>'nemocón','departamento_id'=>11],
            ['codigo'=>25488,'nombre'=>'nilo','departamento_id'=>11],
            ['codigo'=>25489,'nombre'=>'nimaima','departamento_id'=>11],
            ['codigo'=>25491,'nombre'=>'nocaima','departamento_id'=>11],
            ['codigo'=>25506,'nombre'=>'venecia','departamento_id'=>11],
            ['codigo'=>25513,'nombre'=>'pacho','departamento_id'=>11],
            ['codigo'=>25518,'nombre'=>'paime','departamento_id'=>11],
            ['codigo'=>25524,'nombre'=>'pandi','departamento_id'=>11],
            ['codigo'=>25530,'nombre'=>'paratebueno','departamento_id'=>11],
            ['codigo'=>25535,'nombre'=>'pasca','departamento_id'=>11],
            ['codigo'=>25572,'nombre'=>'puerto salgar','departamento_id'=>11],
            ['codigo'=>25580,'nombre'=>'pulí','departamento_id'=>11],
            ['codigo'=>25592,'nombre'=>'quebradanegra','departamento_id'=>11],
            ['codigo'=>25594,'nombre'=>'quetame','departamento_id'=>11],
            ['codigo'=>25596,'nombre'=>'quipile','departamento_id'=>11],
            ['codigo'=>25599,'nombre'=>'apulo','departamento_id'=>11],
            ['codigo'=>25612,'nombre'=>'ricaurte','departamento_id'=>11],
            ['codigo'=>25645,'nombre'=>'san antonio del tequendama','departamento_id'=>11],
            ['codigo'=>25649,'nombre'=>'san bernardo','departamento_id'=>11],
            ['codigo'=>25653,'nombre'=>'san cayetano','departamento_id'=>11],
            ['codigo'=>25658,'nombre'=>'san francisco','departamento_id'=>11],
            ['codigo'=>25662,'nombre'=>'san juan de rioseco','departamento_id'=>11],
            ['codigo'=>25718,'nombre'=>'sasaima','departamento_id'=>11],
            ['codigo'=>25736,'nombre'=>'sesquilé','departamento_id'=>11],
            ['codigo'=>25740,'nombre'=>'sibaté','departamento_id'=>11],
            ['codigo'=>25743,'nombre'=>'silvania','departamento_id'=>11],
            ['codigo'=>25745,'nombre'=>'simijaca','departamento_id'=>11],
            ['codigo'=>25754,'nombre'=>'soacha','departamento_id'=>11],
            ['codigo'=>25758,'nombre'=>'sopó','departamento_id'=>11],
            ['codigo'=>25769,'nombre'=>'subachoque','departamento_id'=>11],
            ['codigo'=>25772,'nombre'=>'suesca','departamento_id'=>11],
            ['codigo'=>25777,'nombre'=>'supatá','departamento_id'=>11],
            ['codigo'=>25779,'nombre'=>'susa','departamento_id'=>11],
            ['codigo'=>25781,'nombre'=>'sutatausa','departamento_id'=>11],
            ['codigo'=>25785,'nombre'=>'tabio','departamento_id'=>11],
            ['codigo'=>25793,'nombre'=>'tausa','departamento_id'=>11],
            ['codigo'=>25797,'nombre'=>'tena','departamento_id'=>11],
            ['codigo'=>25799,'nombre'=>'tenjo','departamento_id'=>11],
            ['codigo'=>25805,'nombre'=>'tibacuy','departamento_id'=>11],
            ['codigo'=>25807,'nombre'=>'tibirita','departamento_id'=>11],
            ['codigo'=>25815,'nombre'=>'tocaima','departamento_id'=>11],
            ['codigo'=>25817,'nombre'=>'tocancipá','departamento_id'=>11],
            ['codigo'=>25823,'nombre'=>'topaipí','departamento_id'=>11],
            ['codigo'=>25839,'nombre'=>'ubalá','departamento_id'=>11],
            ['codigo'=>25841,'nombre'=>'ubaque','departamento_id'=>11],
            ['codigo'=>25843,'nombre'=>'villa de san diego de ubaté','departamento_id'=>11],
            ['codigo'=>25845,'nombre'=>'une','departamento_id'=>11],
            ['codigo'=>25851,'nombre'=>'útica','departamento_id'=>11],
            ['codigo'=>25862,'nombre'=>'vergara','departamento_id'=>11],
            ['codigo'=>25867,'nombre'=>'vianí','departamento_id'=>11],
            ['codigo'=>25871,'nombre'=>'villagómez','departamento_id'=>11],
            ['codigo'=>25873,'nombre'=>'villapinzón','departamento_id'=>11],
            ['codigo'=>25875,'nombre'=>'villeta','departamento_id'=>11],
            ['codigo'=>25878,'nombre'=>'viotá','departamento_id'=>11],
            ['codigo'=>25885,'nombre'=>'yacopí','departamento_id'=>11],
            ['codigo'=>25898,'nombre'=>'zipacón','departamento_id'=>11],
            ['codigo'=>25899,'nombre'=>'zipaquirá','departamento_id'=>11],
            ['codigo'=>27001,'nombre'=>'quibdó','departamento_id'=>12],
            ['codigo'=>27006,'nombre'=>'acandí','departamento_id'=>12],
            ['codigo'=>27025,'nombre'=>'alto baudó','departamento_id'=>12],
            ['codigo'=>27050,'nombre'=>'atrato','departamento_id'=>12],
            ['codigo'=>27073,'nombre'=>'bagadó','departamento_id'=>12],
            ['codigo'=>27075,'nombre'=>'bahía solano','departamento_id'=>12],
            ['codigo'=>27077,'nombre'=>'bajo baudó','departamento_id'=>12],
            ['codigo'=>27099,'nombre'=>'bojayá','departamento_id'=>12],
            ['codigo'=>27135,'nombre'=>'el cantón del san pablo','departamento_id'=>12],
            ['codigo'=>27150,'nombre'=>'carmen del darién','departamento_id'=>12],
            ['codigo'=>27160,'nombre'=>'cértegui','departamento_id'=>12],
            ['codigo'=>27205,'nombre'=>'condoto','departamento_id'=>12],
            ['codigo'=>27245,'nombre'=>'el carmen de atrato','departamento_id'=>12],
            ['codigo'=>27250,'nombre'=>'el litoral del san juan','departamento_id'=>12],
            ['codigo'=>27361,'nombre'=>'istmina','departamento_id'=>12],
            ['codigo'=>27372,'nombre'=>'juradó','departamento_id'=>12],
            ['codigo'=>27413,'nombre'=>'lloró','departamento_id'=>12],
            ['codigo'=>27425,'nombre'=>'medio atrato','departamento_id'=>12],
            ['codigo'=>27430,'nombre'=>'medio baudó','departamento_id'=>12],
            ['codigo'=>27450,'nombre'=>'medio san juan','departamento_id'=>12],
            ['codigo'=>27491,'nombre'=>'nóvita','departamento_id'=>12],
            ['codigo'=>27495,'nombre'=>'nuquí','departamento_id'=>12],
            ['codigo'=>27580,'nombre'=>'río iró','departamento_id'=>12],
            ['codigo'=>27600,'nombre'=>'río quito','departamento_id'=>12],
            ['codigo'=>27615,'nombre'=>'riosucio','departamento_id'=>12],
            ['codigo'=>27660,'nombre'=>'san josé del palmar','departamento_id'=>12],
            ['codigo'=>27745,'nombre'=>'sipí','departamento_id'=>12],
            ['codigo'=>27787,'nombre'=>'tadó','departamento_id'=>12],
            ['codigo'=>27800,'nombre'=>'unguía','departamento_id'=>12],
            ['codigo'=>27810,'nombre'=>'unión panamericana','departamento_id'=>12],
            ['codigo'=>41001,'nombre'=>'neiva','departamento_id'=>13],
            ['codigo'=>41006,'nombre'=>'acevedo','departamento_id'=>13],
            ['codigo'=>41013,'nombre'=>'agrado','departamento_id'=>13],
            ['codigo'=>41016,'nombre'=>'aipe','departamento_id'=>13],
            ['codigo'=>41020,'nombre'=>'algeciras','departamento_id'=>13],
            ['codigo'=>41026,'nombre'=>'altamira','departamento_id'=>13],
            ['codigo'=>41078,'nombre'=>'baraya','departamento_id'=>13],
            ['codigo'=>41132,'nombre'=>'campoalegre','departamento_id'=>13],
            ['codigo'=>41206,'nombre'=>'colombia','departamento_id'=>13],
            ['codigo'=>41244,'nombre'=>'elías','departamento_id'=>13],
            ['codigo'=>41298,'nombre'=>'garzón','departamento_id'=>13],
            ['codigo'=>41306,'nombre'=>'gigante','departamento_id'=>13],
            ['codigo'=>41319,'nombre'=>'guadalupe','departamento_id'=>13],
            ['codigo'=>41349,'nombre'=>'hobo','departamento_id'=>13],
            ['codigo'=>41357,'nombre'=>'íquira','departamento_id'=>13],
            ['codigo'=>41359,'nombre'=>'isnos','departamento_id'=>13],
            ['codigo'=>41378,'nombre'=>'la argentina','departamento_id'=>13],
            ['codigo'=>41396,'nombre'=>'la plata','departamento_id'=>13],
            ['codigo'=>41483,'nombre'=>'nátaga','departamento_id'=>13],
            ['codigo'=>41503,'nombre'=>'oporapa','departamento_id'=>13],
            ['codigo'=>41518,'nombre'=>'paicol','departamento_id'=>13],
            ['codigo'=>41524,'nombre'=>'palermo','departamento_id'=>13],
            ['codigo'=>41530,'nombre'=>'palestina','departamento_id'=>13],
            ['codigo'=>41548,'nombre'=>'pital','departamento_id'=>13],
            ['codigo'=>41551,'nombre'=>'pitalito','departamento_id'=>13],
            ['codigo'=>41615,'nombre'=>'rivera','departamento_id'=>13],
            ['codigo'=>41660,'nombre'=>'saladoblanco','departamento_id'=>13],
            ['codigo'=>41668,'nombre'=>'san agustín','departamento_id'=>13],
            ['codigo'=>41676,'nombre'=>'santa maría','departamento_id'=>13],
            ['codigo'=>41770,'nombre'=>'suaza','departamento_id'=>13],
            ['codigo'=>41791,'nombre'=>'tarqui','departamento_id'=>13],
            ['codigo'=>41797,'nombre'=>'tesalia','departamento_id'=>13],
            ['codigo'=>41799,'nombre'=>'tello','departamento_id'=>13],
            ['codigo'=>41801,'nombre'=>'teruel','departamento_id'=>13],
            ['codigo'=>41807,'nombre'=>'timaná','departamento_id'=>13],
            ['codigo'=>41872,'nombre'=>'villavieja','departamento_id'=>13],
            ['codigo'=>41885,'nombre'=>'yaguará','departamento_id'=>13],
            ['codigo'=>44001,'nombre'=>'riohacha','departamento_id'=>14],
            ['codigo'=>44035,'nombre'=>'albania','departamento_id'=>14],
            ['codigo'=>44078,'nombre'=>'barrancas','departamento_id'=>14],
            ['codigo'=>44090,'nombre'=>'dibulla','departamento_id'=>14],
            ['codigo'=>44098,'nombre'=>'distracción','departamento_id'=>14],
            ['codigo'=>44110,'nombre'=>'el molino','departamento_id'=>14],
            ['codigo'=>44279,'nombre'=>'fonseca','departamento_id'=>14],
            ['codigo'=>44378,'nombre'=>'hatonuevo','departamento_id'=>14],
            ['codigo'=>44420,'nombre'=>'la jagua del pilar','departamento_id'=>14],
            ['codigo'=>44430,'nombre'=>'maicao','departamento_id'=>14],
            ['codigo'=>44560,'nombre'=>'manaure','departamento_id'=>14],
            ['codigo'=>44650,'nombre'=>'san juan del cesar','departamento_id'=>14],
            ['codigo'=>44847,'nombre'=>'uribia','departamento_id'=>14],
            ['codigo'=>44855,'nombre'=>'urumita','departamento_id'=>14],
            ['codigo'=>44874,'nombre'=>'villanueva','departamento_id'=>14],
            ['codigo'=>47001,'nombre'=>'santa marta','departamento_id'=>15],
            ['codigo'=>47030,'nombre'=>'algarrobo','departamento_id'=>15],
            ['codigo'=>47053,'nombre'=>'aracataca','departamento_id'=>15],
            ['codigo'=>47058,'nombre'=>'ariguaní','departamento_id'=>15],
            ['codigo'=>47161,'nombre'=>'cerro de san antonio','departamento_id'=>15],
            ['codigo'=>47170,'nombre'=>'chivolo','departamento_id'=>15],
            ['codigo'=>47189,'nombre'=>'ciénaga','departamento_id'=>15],
            ['codigo'=>47205,'nombre'=>'concordia','departamento_id'=>15],
            ['codigo'=>47245,'nombre'=>'el banco','departamento_id'=>15],
            ['codigo'=>47258,'nombre'=>'el piñón','departamento_id'=>15],
            ['codigo'=>47268,'nombre'=>'el retén','departamento_id'=>15],
            ['codigo'=>47288,'nombre'=>'fundación','departamento_id'=>15],
            ['codigo'=>47318,'nombre'=>'guamal','departamento_id'=>15],
            ['codigo'=>47460,'nombre'=>'nueva granada','departamento_id'=>15],
            ['codigo'=>47541,'nombre'=>'pedraza','departamento_id'=>15],
            ['codigo'=>47545,'nombre'=>'pijiño del carmen','departamento_id'=>15],
            ['codigo'=>47551,'nombre'=>'pivijay','departamento_id'=>15],
            ['codigo'=>47555,'nombre'=>'plato','departamento_id'=>15],
            ['codigo'=>47570,'nombre'=>'puebloviejo','departamento_id'=>15],
            ['codigo'=>47605,'nombre'=>'remolino','departamento_id'=>15],
            ['codigo'=>47660,'nombre'=>'sabanas de san ángel','departamento_id'=>15],
            ['codigo'=>47675,'nombre'=>'salamina','departamento_id'=>15],
            ['codigo'=>47692,'nombre'=>'san sebastián de buenavista','departamento_id'=>15],
            ['codigo'=>47703,'nombre'=>'san zenón','departamento_id'=>15],
            ['codigo'=>47707,'nombre'=>'santa ana','departamento_id'=>15],
            ['codigo'=>47720,'nombre'=>'santa bárbara de pinto','departamento_id'=>15],
            ['codigo'=>47745,'nombre'=>'sitionuevo','departamento_id'=>15],
            ['codigo'=>47798,'nombre'=>'tenerife','departamento_id'=>15],
            ['codigo'=>47960,'nombre'=>'zapayán','departamento_id'=>15],
            ['codigo'=>47980,'nombre'=>'zona bananera','departamento_id'=>15],
            ['codigo'=>50001,'nombre'=>'villavicencio','departamento_id'=>16],
            ['codigo'=>50006,'nombre'=>'acacías','departamento_id'=>16],
            ['codigo'=>50110,'nombre'=>'barranca de upía','departamento_id'=>16],
            ['codigo'=>50124,'nombre'=>'cabuyaro','departamento_id'=>16],
            ['codigo'=>50150,'nombre'=>'castilla la nueva','departamento_id'=>16],
            ['codigo'=>50223,'nombre'=>'cubarral','departamento_id'=>16],
            ['codigo'=>50226,'nombre'=>'cumaral','departamento_id'=>16],
            ['codigo'=>50245,'nombre'=>'el calvario','departamento_id'=>16],
            ['codigo'=>50251,'nombre'=>'el castillo','departamento_id'=>16],
            ['codigo'=>50270,'nombre'=>'el dorado','departamento_id'=>16],
            ['codigo'=>50287,'nombre'=>'fuente de oro','departamento_id'=>16],
            ['codigo'=>50313,'nombre'=>'granada','departamento_id'=>16],
            ['codigo'=>50318,'nombre'=>'guamal','departamento_id'=>16],
            ['codigo'=>50325,'nombre'=>'mapiripán','departamento_id'=>16],
            ['codigo'=>50330,'nombre'=>'mesetas','departamento_id'=>16],
            ['codigo'=>50350,'nombre'=>'la macarena','departamento_id'=>16],
            ['codigo'=>50370,'nombre'=>'uribe','departamento_id'=>16],
            ['codigo'=>50400,'nombre'=>'lejanías','departamento_id'=>16],
            ['codigo'=>50450,'nombre'=>'puerto concordia','departamento_id'=>16],
            ['codigo'=>50568,'nombre'=>'puerto gaitán','departamento_id'=>16],
            ['codigo'=>50573,'nombre'=>'puerto lópez','departamento_id'=>16],
            ['codigo'=>50577,'nombre'=>'puerto lleras','departamento_id'=>16],
            ['codigo'=>50590,'nombre'=>'puerto rico','departamento_id'=>16],
            ['codigo'=>50606,'nombre'=>'restrepo','departamento_id'=>16],
            ['codigo'=>50680,'nombre'=>'san carlos de guaroa','departamento_id'=>16],
            ['codigo'=>50683,'nombre'=>'san juan de arama','departamento_id'=>16],
            ['codigo'=>50686,'nombre'=>'san juanito','departamento_id'=>16],
            ['codigo'=>50689,'nombre'=>'san martín','departamento_id'=>16],
            ['codigo'=>50711,'nombre'=>'vistahermosa','departamento_id'=>16],
            ['codigo'=>52001,'nombre'=>'pasto','departamento_id'=>17],
            ['codigo'=>52019,'nombre'=>'albán','departamento_id'=>17],
            ['codigo'=>52022,'nombre'=>'aldana','departamento_id'=>17],
            ['codigo'=>52036,'nombre'=>'ancuyá','departamento_id'=>17],
            ['codigo'=>52051,'nombre'=>'arboleda','departamento_id'=>17],
            ['codigo'=>52079,'nombre'=>'barbacoas','departamento_id'=>17],
            ['codigo'=>52083,'nombre'=>'belén','departamento_id'=>17],
            ['codigo'=>52110,'nombre'=>'buesaco','departamento_id'=>17],
            ['codigo'=>52203,'nombre'=>'colón','departamento_id'=>17],
            ['codigo'=>52207,'nombre'=>'consacá','departamento_id'=>17],
            ['codigo'=>52210,'nombre'=>'contadero','departamento_id'=>17],
            ['codigo'=>52215,'nombre'=>'córdoba','departamento_id'=>17],
            ['codigo'=>52224,'nombre'=>'cuaspúd','departamento_id'=>17],
            ['codigo'=>52227,'nombre'=>'cumbal','departamento_id'=>17],
            ['codigo'=>52233,'nombre'=>'cumbitara','departamento_id'=>17],
            ['codigo'=>52240,'nombre'=>'chachagüí','departamento_id'=>17],
            ['codigo'=>52250,'nombre'=>'el charco','departamento_id'=>17],
            ['codigo'=>52254,'nombre'=>'el peñol','departamento_id'=>17],
            ['codigo'=>52256,'nombre'=>'el rosario','departamento_id'=>17],
            ['codigo'=>52258,'nombre'=>'el tablón de gómez','departamento_id'=>17],
            ['codigo'=>52260,'nombre'=>'el tambo','departamento_id'=>17],
            ['codigo'=>52287,'nombre'=>'funes','departamento_id'=>17],
            ['codigo'=>52317,'nombre'=>'guachucal','departamento_id'=>17],
            ['codigo'=>52320,'nombre'=>'guaitarilla','departamento_id'=>17],
            ['codigo'=>52323,'nombre'=>'gualmatán','departamento_id'=>17],
            ['codigo'=>52352,'nombre'=>'iles','departamento_id'=>17],
            ['codigo'=>52354,'nombre'=>'imués','departamento_id'=>17],
            ['codigo'=>52356,'nombre'=>'ipiales','departamento_id'=>17],
            ['codigo'=>52378,'nombre'=>'la cruz','departamento_id'=>17],
            ['codigo'=>52381,'nombre'=>'la florida','departamento_id'=>17],
            ['codigo'=>52385,'nombre'=>'la llanada','departamento_id'=>17],
            ['codigo'=>52390,'nombre'=>'la tola','departamento_id'=>17],
            ['codigo'=>52399,'nombre'=>'la unión','departamento_id'=>17],
            ['codigo'=>52405,'nombre'=>'leiva','departamento_id'=>17],
            ['codigo'=>52411,'nombre'=>'linares','departamento_id'=>17],
            ['codigo'=>52418,'nombre'=>'los andes','departamento_id'=>17],
            ['codigo'=>52427,'nombre'=>'magüí','departamento_id'=>17],
            ['codigo'=>52435,'nombre'=>'mallama','departamento_id'=>17],
            ['codigo'=>52473,'nombre'=>'mosquera','departamento_id'=>17],
            ['codigo'=>52480,'nombre'=>'nariño','departamento_id'=>17],
            ['codigo'=>52490,'nombre'=>'olaya herrera','departamento_id'=>17],
            ['codigo'=>52506,'nombre'=>'ospina','departamento_id'=>17],
            ['codigo'=>52520,'nombre'=>'francisco pizarro','departamento_id'=>17],
            ['codigo'=>52540,'nombre'=>'policarpa','departamento_id'=>17],
            ['codigo'=>52560,'nombre'=>'potosí','departamento_id'=>17],
            ['codigo'=>52565,'nombre'=>'providencia','departamento_id'=>17],
            ['codigo'=>52573,'nombre'=>'puerres','departamento_id'=>17],
            ['codigo'=>52585,'nombre'=>'pupiales','departamento_id'=>17],
            ['codigo'=>52612,'nombre'=>'ricaurte','departamento_id'=>17],
            ['codigo'=>52621,'nombre'=>'roberto payán','departamento_id'=>17],
            ['codigo'=>52678,'nombre'=>'samaniego','departamento_id'=>17],
            ['codigo'=>52683,'nombre'=>'sandoná','departamento_id'=>17],
            ['codigo'=>52685,'nombre'=>'san bernardo','departamento_id'=>17],
            ['codigo'=>52687,'nombre'=>'san lorenzo','departamento_id'=>17],
            ['codigo'=>52693,'nombre'=>'san pablo','departamento_id'=>17],
            ['codigo'=>52694,'nombre'=>'san pedro de cartago','departamento_id'=>17],
            ['codigo'=>52696,'nombre'=>'santa bárbara','departamento_id'=>17],
            ['codigo'=>52699,'nombre'=>'santacruz','departamento_id'=>17],
            ['codigo'=>52720,'nombre'=>'sapuyes','departamento_id'=>17],
            ['codigo'=>52786,'nombre'=>'taminango','departamento_id'=>17],
            ['codigo'=>52788,'nombre'=>'tangua','departamento_id'=>17],
            ['codigo'=>52835,'nombre'=>'san andrés de tumaco','departamento_id'=>17],
            ['codigo'=>52838,'nombre'=>'túquerres','departamento_id'=>17],
            ['codigo'=>52885,'nombre'=>'yacuanquer','departamento_id'=>17],
            ['codigo'=>54001,'nombre'=>'cúcuta','departamento_id'=>18],
            ['codigo'=>54003,'nombre'=>'ábrego','departamento_id'=>18],
            ['codigo'=>54051,'nombre'=>'arboledas','departamento_id'=>18],
            ['codigo'=>54099,'nombre'=>'bochalema','departamento_id'=>18],
            ['codigo'=>54109,'nombre'=>'bucarasica','departamento_id'=>18],
            ['codigo'=>54125,'nombre'=>'cácota','departamento_id'=>18],
            ['codigo'=>54128,'nombre'=>'cáchira','departamento_id'=>18],
            ['codigo'=>54172,'nombre'=>'chinácota','departamento_id'=>18],
            ['codigo'=>54174,'nombre'=>'chitagá','departamento_id'=>18],
            ['codigo'=>54206,'nombre'=>'convención','departamento_id'=>18],
            ['codigo'=>54223,'nombre'=>'cucutilla','departamento_id'=>18],
            ['codigo'=>54239,'nombre'=>'durania','departamento_id'=>18],
            ['codigo'=>54245,'nombre'=>'el carmen','departamento_id'=>18],
            ['codigo'=>54250,'nombre'=>'el tarra','departamento_id'=>18],
            ['codigo'=>54261,'nombre'=>'el zulia','departamento_id'=>18],
            ['codigo'=>54313,'nombre'=>'gramalote','departamento_id'=>18],
            ['codigo'=>54344,'nombre'=>'hacarí','departamento_id'=>18],
            ['codigo'=>54347,'nombre'=>'herrán','departamento_id'=>18],
            ['codigo'=>54377,'nombre'=>'labateca','departamento_id'=>18],
            ['codigo'=>54385,'nombre'=>'la esperanza','departamento_id'=>18],
            ['codigo'=>54398,'nombre'=>'la playa','departamento_id'=>18],
            ['codigo'=>54405,'nombre'=>'los patios','departamento_id'=>18],
            ['codigo'=>54418,'nombre'=>'lourdes','departamento_id'=>18],
            ['codigo'=>54480,'nombre'=>'mutiscua','departamento_id'=>18],
            ['codigo'=>54498,'nombre'=>'ocaña','departamento_id'=>18],
            ['codigo'=>54518,'nombre'=>'pamplona','departamento_id'=>18],
            ['codigo'=>54520,'nombre'=>'pamplonita','departamento_id'=>18],
            ['codigo'=>54553,'nombre'=>'puerto santander','departamento_id'=>18],
            ['codigo'=>54599,'nombre'=>'ragonvalia','departamento_id'=>18],
            ['codigo'=>54660,'nombre'=>'salazar','departamento_id'=>18],
            ['codigo'=>54670,'nombre'=>'san calixto','departamento_id'=>18],
            ['codigo'=>54673,'nombre'=>'san cayetano','departamento_id'=>18],
            ['codigo'=>54680,'nombre'=>'santiago','departamento_id'=>18],
            ['codigo'=>54720,'nombre'=>'sardinata','departamento_id'=>18],
            ['codigo'=>54743,'nombre'=>'silos','departamento_id'=>18],
            ['codigo'=>54800,'nombre'=>'teorama','departamento_id'=>18],
            ['codigo'=>54810,'nombre'=>'tibú','departamento_id'=>18],
            ['codigo'=>54820,'nombre'=>'toledo','departamento_id'=>18],
            ['codigo'=>54871,'nombre'=>'villa caro','departamento_id'=>18],
            ['codigo'=>54874,'nombre'=>'villa del rosario','departamento_id'=>18],
            ['codigo'=>63001,'nombre'=>'armenia','departamento_id'=>19],
            ['codigo'=>63111,'nombre'=>'buenavista','departamento_id'=>19],
            ['codigo'=>63130,'nombre'=>'calarcá','departamento_id'=>19],
            ['codigo'=>63190,'nombre'=>'circasia','departamento_id'=>19],
            ['codigo'=>63212,'nombre'=>'córdoba','departamento_id'=>19],
            ['codigo'=>63272,'nombre'=>'filandia','departamento_id'=>19],
            ['codigo'=>63302,'nombre'=>'génova','departamento_id'=>19],
            ['codigo'=>63401,'nombre'=>'la tebaida','departamento_id'=>19],
            ['codigo'=>63470,'nombre'=>'montenegro','departamento_id'=>19],
            ['codigo'=>63548,'nombre'=>'pijao','departamento_id'=>19],
            ['codigo'=>63594,'nombre'=>'quimbaya','departamento_id'=>19],
            ['codigo'=>63690,'nombre'=>'salento','departamento_id'=>19],
            ['codigo'=>66001,'nombre'=>'pereira','departamento_id'=>20],
            ['codigo'=>66045,'nombre'=>'apía','departamento_id'=>20],
            ['codigo'=>66075,'nombre'=>'balboa','departamento_id'=>20],
            ['codigo'=>66088,'nombre'=>'belén de umbría','departamento_id'=>20],
            ['codigo'=>66170,'nombre'=>'dosquebradas','departamento_id'=>20],
            ['codigo'=>66318,'nombre'=>'guática','departamento_id'=>20],
            ['codigo'=>66383,'nombre'=>'la celia','departamento_id'=>20],
            ['codigo'=>66400,'nombre'=>'la virginia','departamento_id'=>20],
            ['codigo'=>66440,'nombre'=>'marsella','departamento_id'=>20],
            ['codigo'=>66456,'nombre'=>'mistrató','departamento_id'=>20],
            ['codigo'=>66572,'nombre'=>'pueblo rico','departamento_id'=>20],
            ['codigo'=>66594,'nombre'=>'quinchía','departamento_id'=>20],
            ['codigo'=>66682,'nombre'=>'santa rosa de cabal','departamento_id'=>20],
            ['codigo'=>66687,'nombre'=>'santuario','departamento_id'=>20],
            ['codigo'=>68001,'nombre'=>'bucaramanga','departamento_id'=>21],
            ['codigo'=>68013,'nombre'=>'aguada','departamento_id'=>21],
            ['codigo'=>68020,'nombre'=>'albania','departamento_id'=>21],
            ['codigo'=>68051,'nombre'=>'aratoca','departamento_id'=>21],
            ['codigo'=>68077,'nombre'=>'barbosa','departamento_id'=>21],
            ['codigo'=>68079,'nombre'=>'barichara','departamento_id'=>21],
            ['codigo'=>68081,'nombre'=>'barrancabermeja','departamento_id'=>21],
            ['codigo'=>68092,'nombre'=>'betulia','departamento_id'=>21],
            ['codigo'=>68101,'nombre'=>'bolívar','departamento_id'=>21],
            ['codigo'=>68121,'nombre'=>'cabrera','departamento_id'=>21],
            ['codigo'=>68132,'nombre'=>'california','departamento_id'=>21],
            ['codigo'=>68147,'nombre'=>'capitanejo','departamento_id'=>21],
            ['codigo'=>68152,'nombre'=>'carcasí','departamento_id'=>21],
            ['codigo'=>68160,'nombre'=>'cepitá','departamento_id'=>21],
            ['codigo'=>68162,'nombre'=>'cerrito','departamento_id'=>21],
            ['codigo'=>68167,'nombre'=>'charalá','departamento_id'=>21],
            ['codigo'=>68169,'nombre'=>'charta','departamento_id'=>21],
            ['codigo'=>68176,'nombre'=>'chima','departamento_id'=>21],
            ['codigo'=>68179,'nombre'=>'chipatá','departamento_id'=>21],
            ['codigo'=>68190,'nombre'=>'cimitarra','departamento_id'=>21],
            ['codigo'=>68207,'nombre'=>'concepción','departamento_id'=>21],
            ['codigo'=>68209,'nombre'=>'confines','departamento_id'=>21],
            ['codigo'=>68211,'nombre'=>'contratación','departamento_id'=>21],
            ['codigo'=>68217,'nombre'=>'coromoro','departamento_id'=>21],
            ['codigo'=>68229,'nombre'=>'curití','departamento_id'=>21],
            ['codigo'=>68235,'nombre'=>'el carmen de chucurí','departamento_id'=>21],
            ['codigo'=>68245,'nombre'=>'el guacamayo','departamento_id'=>21],
            ['codigo'=>68250,'nombre'=>'el peñón','departamento_id'=>21],
            ['codigo'=>68255,'nombre'=>'el playón','departamento_id'=>21],
            ['codigo'=>68264,'nombre'=>'encino','departamento_id'=>21],
            ['codigo'=>68266,'nombre'=>'enciso','departamento_id'=>21],
            ['codigo'=>68271,'nombre'=>'florián','departamento_id'=>21],
            ['codigo'=>68276,'nombre'=>'floridablanca','departamento_id'=>21],
            ['codigo'=>68296,'nombre'=>'galán','departamento_id'=>21],
            ['codigo'=>68298,'nombre'=>'gámbita','departamento_id'=>21],
            ['codigo'=>68307,'nombre'=>'girón','departamento_id'=>21],
            ['codigo'=>68318,'nombre'=>'guaca','departamento_id'=>21],
            ['codigo'=>68320,'nombre'=>'guadalupe','departamento_id'=>21],
            ['codigo'=>68322,'nombre'=>'guapotá','departamento_id'=>21],
            ['codigo'=>68324,'nombre'=>'guavatá','departamento_id'=>21],
            ['codigo'=>68327,'nombre'=>'güepsa','departamento_id'=>21],
            ['codigo'=>68344,'nombre'=>'hato','departamento_id'=>21],
            ['codigo'=>68368,'nombre'=>'jesús maría','departamento_id'=>21],
            ['codigo'=>68370,'nombre'=>'jordán','departamento_id'=>21],
            ['codigo'=>68377,'nombre'=>'la belleza','departamento_id'=>21],
            ['codigo'=>68385,'nombre'=>'landázuri','departamento_id'=>21],
            ['codigo'=>68397,'nombre'=>'la paz','departamento_id'=>21],
            ['codigo'=>68406,'nombre'=>'lebrija','departamento_id'=>21],
            ['codigo'=>68418,'nombre'=>'los santos','departamento_id'=>21],
            ['codigo'=>68425,'nombre'=>'macaravita','departamento_id'=>21],
            ['codigo'=>68432,'nombre'=>'málaga','departamento_id'=>21],
            ['codigo'=>68444,'nombre'=>'matanza','departamento_id'=>21],
            ['codigo'=>68464,'nombre'=>'mogotes','departamento_id'=>21],
            ['codigo'=>68468,'nombre'=>'molagavita','departamento_id'=>21],
            ['codigo'=>68498,'nombre'=>'ocamonte','departamento_id'=>21],
            ['codigo'=>68500,'nombre'=>'oiba','departamento_id'=>21],
            ['codigo'=>68502,'nombre'=>'onzaga','departamento_id'=>21],
            ['codigo'=>68522,'nombre'=>'palmar','departamento_id'=>21],
            ['codigo'=>68524,'nombre'=>'palmas del socorro','departamento_id'=>21],
            ['codigo'=>68533,'nombre'=>'páramo','departamento_id'=>21],
            ['codigo'=>68547,'nombre'=>'piedecuesta','departamento_id'=>21],
            ['codigo'=>68549,'nombre'=>'pinchote','departamento_id'=>21],
            ['codigo'=>68572,'nombre'=>'puente nacional','departamento_id'=>21],
            ['codigo'=>68573,'nombre'=>'puerto parra','departamento_id'=>21],
            ['codigo'=>68575,'nombre'=>'puerto wilches','departamento_id'=>21],
            ['codigo'=>68615,'nombre'=>'rionegro','departamento_id'=>21],
            ['codigo'=>68655,'nombre'=>'sabana de torres','departamento_id'=>21],
            ['codigo'=>68669,'nombre'=>'san andrés','departamento_id'=>21],
            ['codigo'=>68673,'nombre'=>'san benito','departamento_id'=>21],
            ['codigo'=>68679,'nombre'=>'san gil','departamento_id'=>21],
            ['codigo'=>68682,'nombre'=>'san joaquín','departamento_id'=>21],
            ['codigo'=>68684,'nombre'=>'san josé de miranda','departamento_id'=>21],
            ['codigo'=>68686,'nombre'=>'san miguel','departamento_id'=>21],
            ['codigo'=>68689,'nombre'=>'san vicente de chucurí','departamento_id'=>21],
            ['codigo'=>68705,'nombre'=>'santa bárbara','departamento_id'=>21],
            ['codigo'=>68720,'nombre'=>'santa helena del opón','departamento_id'=>21],
            ['codigo'=>68745,'nombre'=>'simacota','departamento_id'=>21],
            ['codigo'=>68755,'nombre'=>'socorro','departamento_id'=>21],
            ['codigo'=>68770,'nombre'=>'suaita','departamento_id'=>21],
            ['codigo'=>68773,'nombre'=>'sucre','departamento_id'=>21],
            ['codigo'=>68780,'nombre'=>'suratá','departamento_id'=>21],
            ['codigo'=>68820,'nombre'=>'tona','departamento_id'=>21],
            ['codigo'=>68855,'nombre'=>'valle de san josé','departamento_id'=>21],
            ['codigo'=>68861,'nombre'=>'vélez','departamento_id'=>21],
            ['codigo'=>68867,'nombre'=>'vetas','departamento_id'=>21],
            ['codigo'=>68872,'nombre'=>'villanueva','departamento_id'=>21],
            ['codigo'=>68895,'nombre'=>'zapatoca','departamento_id'=>21],
            ['codigo'=>70001,'nombre'=>'sincelejo','departamento_id'=>22],
            ['codigo'=>70110,'nombre'=>'buenavista','departamento_id'=>22],
            ['codigo'=>70124,'nombre'=>'caimito','departamento_id'=>22],
            ['codigo'=>70204,'nombre'=>'colosó','departamento_id'=>22],
            ['codigo'=>70215,'nombre'=>'corozal','departamento_id'=>22],
            ['codigo'=>70221,'nombre'=>'coveñas','departamento_id'=>22],
            ['codigo'=>70230,'nombre'=>'chalán','departamento_id'=>22],
            ['codigo'=>70233,'nombre'=>'el roble','departamento_id'=>22],
            ['codigo'=>70235,'nombre'=>'galeras','departamento_id'=>22],
            ['codigo'=>70265,'nombre'=>'guaranda','departamento_id'=>22],
            ['codigo'=>70400,'nombre'=>'la unión','departamento_id'=>22],
            ['codigo'=>70418,'nombre'=>'los palmitos','departamento_id'=>22],
            ['codigo'=>70429,'nombre'=>'majagual','departamento_id'=>22],
            ['codigo'=>70473,'nombre'=>'morroa','departamento_id'=>22],
            ['codigo'=>70508,'nombre'=>'ovejas','departamento_id'=>22],
            ['codigo'=>70523,'nombre'=>'palmito','departamento_id'=>22],
            ['codigo'=>70670,'nombre'=>'sampués','departamento_id'=>22],
            ['codigo'=>70678,'nombre'=>'san benito abad','departamento_id'=>22],
            ['codigo'=>70702,'nombre'=>'san juan de betulia','departamento_id'=>22],
            ['codigo'=>70708,'nombre'=>'san marcos','departamento_id'=>22],
            ['codigo'=>70713,'nombre'=>'san onofre','departamento_id'=>22],
            ['codigo'=>70717,'nombre'=>'san pedro','departamento_id'=>22],
            ['codigo'=>70742,'nombre'=>'san luis de sincé','departamento_id'=>22],
            ['codigo'=>70771,'nombre'=>'sucre','departamento_id'=>22],
            ['codigo'=>70820,'nombre'=>'santiago de tolú','departamento_id'=>22],
            ['codigo'=>70823,'nombre'=>'tolú viejo','departamento_id'=>22],
            ['codigo'=>73001,'nombre'=>'ibagué','departamento_id'=>23],
            ['codigo'=>73024,'nombre'=>'alpujarra','departamento_id'=>23],
            ['codigo'=>73026,'nombre'=>'alvarado','departamento_id'=>23],
            ['codigo'=>73030,'nombre'=>'ambalema','departamento_id'=>23],
            ['codigo'=>73043,'nombre'=>'anzoátegui','departamento_id'=>23],
            ['codigo'=>73055,'nombre'=>'armero guayabal','departamento_id'=>23],
            ['codigo'=>73067,'nombre'=>'ataco','departamento_id'=>23],
            ['codigo'=>73124,'nombre'=>'cajamarca','departamento_id'=>23],
            ['codigo'=>73148,'nombre'=>'carmen de apicalá','departamento_id'=>23],
            ['codigo'=>73152,'nombre'=>'casabianca','departamento_id'=>23],
            ['codigo'=>73168,'nombre'=>'chaparral','departamento_id'=>23],
            ['codigo'=>73200,'nombre'=>'coello','departamento_id'=>23],
            ['codigo'=>73217,'nombre'=>'coyaima','departamento_id'=>23],
            ['codigo'=>73226,'nombre'=>'cunday','departamento_id'=>23],
            ['codigo'=>73236,'nombre'=>'dolores','departamento_id'=>23],
            ['codigo'=>73268,'nombre'=>'espinal','departamento_id'=>23],
            ['codigo'=>73270,'nombre'=>'falan','departamento_id'=>23],
            ['codigo'=>73275,'nombre'=>'flandes','departamento_id'=>23],
            ['codigo'=>73283,'nombre'=>'fresno','departamento_id'=>23],
            ['codigo'=>73319,'nombre'=>'guamo','departamento_id'=>23],
            ['codigo'=>73347,'nombre'=>'herveo','departamento_id'=>23],
            ['codigo'=>73349,'nombre'=>'honda','departamento_id'=>23],
            ['codigo'=>73352,'nombre'=>'icononzo','departamento_id'=>23],
            ['codigo'=>73408,'nombre'=>'lérida','departamento_id'=>23],
            ['codigo'=>73411,'nombre'=>'líbano','departamento_id'=>23],
            ['codigo'=>73443,'nombre'=>'san sebastián de mariquita','departamento_id'=>23],
            ['codigo'=>73449,'nombre'=>'melgar','departamento_id'=>23],
            ['codigo'=>73461,'nombre'=>'murillo','departamento_id'=>23],
            ['codigo'=>73483,'nombre'=>'natagaima','departamento_id'=>23],
            ['codigo'=>73504,'nombre'=>'ortega','departamento_id'=>23],
            ['codigo'=>73520,'nombre'=>'palocabildo','departamento_id'=>23],
            ['codigo'=>73547,'nombre'=>'piedras','departamento_id'=>23],
            ['codigo'=>73555,'nombre'=>'planadas','departamento_id'=>23],
            ['codigo'=>73563,'nombre'=>'prado','departamento_id'=>23],
            ['codigo'=>73585,'nombre'=>'purificación','departamento_id'=>23],
            ['codigo'=>73616,'nombre'=>'rioblanco','departamento_id'=>23],
            ['codigo'=>73622,'nombre'=>'roncesvalles','departamento_id'=>23],
            ['codigo'=>73624,'nombre'=>'rovira','departamento_id'=>23],
            ['codigo'=>73671,'nombre'=>'saldaña','departamento_id'=>23],
            ['codigo'=>73675,'nombre'=>'san antonio','departamento_id'=>23],
            ['codigo'=>73678,'nombre'=>'san luis','departamento_id'=>23],
            ['codigo'=>73686,'nombre'=>'santa isabel','departamento_id'=>23],
            ['codigo'=>73770,'nombre'=>'suárez','departamento_id'=>23],
            ['codigo'=>73854,'nombre'=>'valle de san juan','departamento_id'=>23],
            ['codigo'=>73861,'nombre'=>'venadillo','departamento_id'=>23],
            ['codigo'=>73870,'nombre'=>'villahermosa','departamento_id'=>23],
            ['codigo'=>73873,'nombre'=>'villarrica','departamento_id'=>23],
            ['codigo'=>76001,'nombre'=>'cali','departamento_id'=>24],
            ['codigo'=>76020,'nombre'=>'alcalá','departamento_id'=>24],
            ['codigo'=>76036,'nombre'=>'andalucía','departamento_id'=>24],
            ['codigo'=>76041,'nombre'=>'ansermanuevo','departamento_id'=>24],
            ['codigo'=>76054,'nombre'=>'argelia','departamento_id'=>24],
            ['codigo'=>76100,'nombre'=>'bolívar','departamento_id'=>24],
            ['codigo'=>76109,'nombre'=>'buenaventura','departamento_id'=>24],
            ['codigo'=>76111,'nombre'=>'guadalajara de buga','departamento_id'=>24],
            ['codigo'=>76113,'nombre'=>'bugalagrande','departamento_id'=>24],
            ['codigo'=>76122,'nombre'=>'caicedonia','departamento_id'=>24],
            ['codigo'=>76126,'nombre'=>'calima','departamento_id'=>24],
            ['codigo'=>76130,'nombre'=>'candelaria','departamento_id'=>24],
            ['codigo'=>76147,'nombre'=>'cartago','departamento_id'=>24],
            ['codigo'=>76233,'nombre'=>'dagua','departamento_id'=>24],
            ['codigo'=>76243,'nombre'=>'el águila','departamento_id'=>24],
            ['codigo'=>76246,'nombre'=>'el cairo','departamento_id'=>24],
            ['codigo'=>76248,'nombre'=>'el cerrito','departamento_id'=>24],
            ['codigo'=>76250,'nombre'=>'el dovio','departamento_id'=>24],
            ['codigo'=>76275,'nombre'=>'florida','departamento_id'=>24],
            ['codigo'=>76306,'nombre'=>'ginebra','departamento_id'=>24],
            ['codigo'=>76318,'nombre'=>'guacarí','departamento_id'=>24],
            ['codigo'=>76364,'nombre'=>'jamundí','departamento_id'=>24],
            ['codigo'=>76377,'nombre'=>'la cumbre','departamento_id'=>24],
            ['codigo'=>76400,'nombre'=>'la unión','departamento_id'=>24],
            ['codigo'=>76403,'nombre'=>'la victoria','departamento_id'=>24],
            ['codigo'=>76497,'nombre'=>'obando','departamento_id'=>24],
            ['codigo'=>76520,'nombre'=>'palmira','departamento_id'=>24],
            ['codigo'=>76563,'nombre'=>'pradera','departamento_id'=>24],
            ['codigo'=>76606,'nombre'=>'restrepo','departamento_id'=>24],
            ['codigo'=>76616,'nombre'=>'riofrío','departamento_id'=>24],
            ['codigo'=>76622,'nombre'=>'roldanillo','departamento_id'=>24],
            ['codigo'=>76670,'nombre'=>'san pedro','departamento_id'=>24],
            ['codigo'=>76736,'nombre'=>'sevilla','departamento_id'=>24],
            ['codigo'=>76823,'nombre'=>'toro','departamento_id'=>24],
            ['codigo'=>76828,'nombre'=>'trujillo','departamento_id'=>24],
            ['codigo'=>76834,'nombre'=>'tuluá','departamento_id'=>24],
            ['codigo'=>76845,'nombre'=>'ulloa','departamento_id'=>24],
            ['codigo'=>76863,'nombre'=>'versalles','departamento_id'=>24],
            ['codigo'=>76869,'nombre'=>'vijes','departamento_id'=>24],
            ['codigo'=>76890,'nombre'=>'yotoco','departamento_id'=>24],
            ['codigo'=>76892,'nombre'=>'yumbo','departamento_id'=>24],
            ['codigo'=>76895,'nombre'=>'zarzal','departamento_id'=>24],
            ['codigo'=>81001,'nombre'=>'arauca','departamento_id'=>25],
            ['codigo'=>81065,'nombre'=>'arauquita','departamento_id'=>25],
            ['codigo'=>81220,'nombre'=>'cravo norte','departamento_id'=>25],
            ['codigo'=>81300,'nombre'=>'fortul','departamento_id'=>25],
            ['codigo'=>81591,'nombre'=>'puerto rondón','departamento_id'=>25],
            ['codigo'=>81736,'nombre'=>'saravena','departamento_id'=>25],
            ['codigo'=>81794,'nombre'=>'tame','departamento_id'=>25],
            ['codigo'=>85001,'nombre'=>'yopal','departamento_id'=>26],
            ['codigo'=>85010,'nombre'=>'aguazul','departamento_id'=>26],
            ['codigo'=>85015,'nombre'=>'chámeza','departamento_id'=>26],
            ['codigo'=>85125,'nombre'=>'hato corozal','departamento_id'=>26],
            ['codigo'=>85136,'nombre'=>'la salina','departamento_id'=>26],
            ['codigo'=>85139,'nombre'=>'maní','departamento_id'=>26],
            ['codigo'=>85162,'nombre'=>'monterrey','departamento_id'=>26],
            ['codigo'=>85225,'nombre'=>'nunchía','departamento_id'=>26],
            ['codigo'=>85230,'nombre'=>'orocué','departamento_id'=>26],
            ['codigo'=>85250,'nombre'=>'paz de ariporo','departamento_id'=>26],
            ['codigo'=>85263,'nombre'=>'pore','departamento_id'=>26],
            ['codigo'=>85279,'nombre'=>'recetor','departamento_id'=>26],
            ['codigo'=>85300,'nombre'=>'sabanalarga','departamento_id'=>26],
            ['codigo'=>85315,'nombre'=>'sácama','departamento_id'=>26],
            ['codigo'=>85325,'nombre'=>'san luis de palenque','departamento_id'=>26],
            ['codigo'=>85400,'nombre'=>'támara','departamento_id'=>26],
            ['codigo'=>85410,'nombre'=>'tauramena','departamento_id'=>26],
            ['codigo'=>85430,'nombre'=>'trinidad','departamento_id'=>26],
            ['codigo'=>85440,'nombre'=>'villanueva','departamento_id'=>26],
            ['codigo'=>86001,'nombre'=>'mocoa','departamento_id'=>27],
            ['codigo'=>86219,'nombre'=>'colón','departamento_id'=>27],
            ['codigo'=>86320,'nombre'=>'orito','departamento_id'=>27],
            ['codigo'=>86568,'nombre'=>'puerto asís','departamento_id'=>27],
            ['codigo'=>86569,'nombre'=>'puerto caicedo','departamento_id'=>27],
            ['codigo'=>86571,'nombre'=>'puerto guzmán','departamento_id'=>27],
            ['codigo'=>86573,'nombre'=>'puerto leguízamo','departamento_id'=>27],
            ['codigo'=>86749,'nombre'=>'sibundoy','departamento_id'=>27],
            ['codigo'=>86755,'nombre'=>'san francisco','departamento_id'=>27],
            ['codigo'=>86757,'nombre'=>'san miguel','departamento_id'=>27],
            ['codigo'=>86760,'nombre'=>'santiago','departamento_id'=>27],
            ['codigo'=>86865,'nombre'=>'valle del guamuez','departamento_id'=>27],
            ['codigo'=>86885,'nombre'=>'villagarzón','departamento_id'=>27],
            ['codigo'=>88001,'nombre'=>'san andrés','departamento_id'=>28],
            ['codigo'=>88564,'nombre'=>'providencia','departamento_id'=>28],
            ['codigo'=>91001,'nombre'=>'leticia','departamento_id'=>29],
            ['codigo'=>91540,'nombre'=>'puerto nariño','departamento_id'=>29],
            ['codigo'=>94001,'nombre'=>'puerto inírida','departamento_id'=>30],
            ['codigo'=>95001,'nombre'=>'san josé del guaviare','departamento_id'=>31],
            ['codigo'=>95015,'nombre'=>'calamar','departamento_id'=>31],
            ['codigo'=>95025,'nombre'=>'el retorno','departamento_id'=>31],
            ['codigo'=>95200,'nombre'=>'miraflores','departamento_id'=>31],
            ['codigo'=>97001,'nombre'=>'mitú','departamento_id'=>32],
            ['codigo'=>97161,'nombre'=>'carurú','departamento_id'=>32],
            ['codigo'=>97666,'nombre'=>'taraira','departamento_id'=>32],
            ['codigo'=>99001,'nombre'=>'puerto carreño','departamento_id'=>33],
            ['codigo'=>99524,'nombre'=>'la primavera','departamento_id'=>33],
            ['codigo'=>99624,'nombre'=>'santa rosalía','departamento_id'=>33],
            ['codigo'=>99773,'nombre'=>'cumaribo','departamento_id'=>33],
        ]);
    }
}
